### PR TITLE
Handle `piece_width` for specific language (TH)

### PR DESCRIPTION
**Pull request by luangtatipsy**
Some languages (in this case Thai) contain vowels, and tone marks that are not placed horizontally, they are placed on the top or bottom of consonants.  This pull request is modified, in order to handle those characters.

This is an example of before and after results.
### __Before__
before
### __After__
after

### CODE REVIEW

**Comment by Belval** [comment]
Sorry I've been slow to respond/review, but this is a great PR! 

Before I merge it, are all the fonts you added free to redistribute? This is important because the project could get shut down over IP concerns if I merge changes that include non-free fonts.

Are they all from Google Fonts?

**Comment by luangtatipsy** [comment]
> Sorry I've been slow to respond/review, but this is a great PR!
> 
> Before I merge it, are all the fonts you added free to redistribute? This is important because the project could get shut down over IP concerns if I merge changes that include non-free fonts.
> 
> Are they all from Google Fonts?

Of course, I downloaded them all from Google Fonts.

**Comment by Belval** [comment]
I will test and merge this PR this week, thank you for your contribution!

**Comment by Belval** [comment]
Thank you for your contribution.

**Comment by luangtatipsy** [comment]
@Belval I've just noticed that Thai fonts have not existed, installed via `pip`. Can you please add a single line in `MANIFEST.in` to include Thai fonts as well?
```
include trdg/fonts/th/*
```

**Pull request merged**
