### PR TITLE
Add -obb parameter to output bounding boxes

### PR DESCRIPTION
**Pull request by Belval**
Follow-up to #107, when using the `-obb 1` parameter, the CLI tool will output a `txt` file with one line per character with the matching bounding boxes.

Current format is `x1 y1 x2 y2` but it could be changed to fit @yyyash8 use case (or better yet, lets make a parameter for it).

Still need to add tests.

TEST1_0
out

```
4 12 16 27
17 12 26 27
28 12 38 27
38 12 50 27
51 12 57 27
```

Code used to render the bounding boxes: 

```py
import sys
from PIL import Image, ImageDraw

def main(argv):
    img = Image.open(argv[1])
    bboxes = []
    with open(argv[2], "r") as f:
        for line in f.readlines():
            line = line[:-1]
            bboxes.append([int(coord) for coord in line.split(" ")])

    d = ImageDraw.Draw(img)

    for bbox in bboxes:
        d.rectangle(bbox, outline="green")

    img.save("out.png")

if __name__=='__main__':
    main(sys.argv)
```

### CODE REVIEW

**Comment by gulnazaki** [comment]
when the string has spaces we get a bbox for only the first word

**Comment by gulnazaki** [comment]
fixed with https://github.com/Belval/TextRecognitionDataGenerator/pull/150

**Comment by dkopljar27** [comment]
Hey, first of all thx for the project :) 
I think that code is not working properly when blur is activated, as I am not seeing all characters in the output txt file.

I think that this is causing the problem:
data_generator.py
`final_mask = background_mask.filter(gaussian_filter)`

utils.py 
`letter = np.where(np.all(mask_arr == color_tuple, axis=-1))`

**Comment by mgersalan** [comment]
`python trdg/run.py -c 100 -obb 1 --output_dir mask_Test_2 -i /Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/texts/random_2.txt -f 256 -om 1`'

this command does not generate any txt output for the masks, it only generates masks and png images. What am I missing here? @Belval

**Comment by cesarandreslopez** [comment]
> `python trdg/run.py -c 100 -obb 1 --output_dir mask_Test_2 -i /Users/gurersalan/Documents/TextRecognitionDataGenerator/trdg/texts/random_2.txt -f 256 -om 1`'
> 
> this command does not generate any txt output for the masks, it only generates masks and png images. What am I missing here? @Belval

Check if you have pip trdg package installed. If you do, uninstall it.

**Comment by srividya-p** [comment]
@Belval thanks a lot for this code, However when it comes to ligatures the bounding boxes cover the whole word instead of a character. 
I have added this Indian language named Gujarati. (Script is similar to Hindi)

These are the bounding boxes _without_ the `--word_split` option, however the text is not correct according to the language (which is a ligature based script).

image


Here I have used the `--word_split` option and the text is perfect but as I mentioned before the bounding boxes encompass the whole word.

image

Can this case be handled?
Any sort of help/insight is deeply appreciated!

**Comment by Belval** [comment]
Hey @srividya-p this is surprisingly hard to fix because the ligature will change the size of the character, but Pillow does not give me the ligature size, only the character size.

The current PR only really infers the size from the word crop mask so it's not really suitable for ligature at all. If you want to fix it yourself I would start in https://github.com/Belval/TextRecognitionDataGenerator/blob/master/trdg/computer_text_generator.py#L41 and see if the character size pre-ligature is close enough for your use case. If it is you can probably just return character bounding boxes from the same file and simply transform them through the various steps of the generation process in https://github.com/Belval/TextRecognitionDataGenerator/blob/master/trdg/data_generator.py#L70.

**Comment by srividya-p** [comment]
> Hey @srividya-p this is surprisingly hard to fix because the ligature will change the size of the character, but Pillow does not give me the ligature size, only the character size.

Thank you very much for your response! Since you let me know where to start, I was able to understand the `--word_split ` code and modify the piece widths according to my needs.

image

Of course, I could do this only because I am aware of the unicode for ligature characters specific to this language. Like you mentioned generalising this with Pillow seems difficult.

Thanks once again for making such a great utility! This project along with the `-obb` feature has saved hours of my time in dataset generation 😄!

**Comment by Belval** [comment]
@srividya-p Do you have your code somewhere? I'd be interested in seeing how you fixed the issue.

**Comment by srividya-p** [comment]
> @srividya-p Do you have your code somewhere? I'd be interested in seeing how you fixed the issue.

@Belval Yeah sure. This is a modified version of computer_text_generator.py. I have added my approach in Lines 28 - 87

https://github.com/srividya-p/TIRF-Gujrati-Script-Recognition/blob/194d99ee737a04cfdf617703033799b110853526/trdg/computer_text_generator_gujarati.py#L28

**Pull request closed without merging**
