### PR TITLE
add dicts for many languages

### PR DESCRIPTION
**Pull request by rkcosmos**
Hello,

First of all, thanks a lot for creating this text generator. We used it for [EasyOCR](https://github.com/JaidedAI/EasyOCR) project. I think it's time we give a small contribution back to your project. This PR contains a lot of dictionary for 50+ languages. It's not only my effort but rather a community's work to create OCR system that works for their language.

Thanks a lot,
Rakpong

### CODE REVIEW

**Comment by Belval** [comment]
I didn't know EasyOCR used my project, I am very glad that you go some use out of it!

As for the dictionaries that's great! Thank you!

**Comment by GokulNC** [comment]
@rkcosmos Can you please explain if you made any changes to the code of `trdg` to get it working properly for all non-Latin-based langauges?
Also what are the fonts that you used for each language? (if any)

It'd be really helpful if you can briefly mention about that 🙂

**Comment by Belval** [comment]
@GokulNC you can find font for pretty much all languages on Google Fonts: https://fonts.google.com/

Is there a particular language that you are having trouble with?

**Comment by GokulNC** [comment]
@Belval Yes. For example, I am trying to generate data for Hindi (Devanagari script).

This is the text:
```
देवतात्मों नति जोहारो पोहना मालिंके
```

And this is the output:
image

My environment:
- OS: Ubuntu 18.04
- Python: 3.6.9
- Tried [fonts from Google](https://fonts.google.com/) as well as Indic Fonts (`sudo apt install fonts-indic`)
- Tried both without and with [`RAQM` installed](https://stackoverflow.com/a/61048616)
  - Note: After installing `libraqm`, I had to rebuild `Pillow`

Any pointers on how to fix would be great!

**Comment by iknoorjobs** [comment]
Hi @GokulNC 

This does solve the complete problem. There an issue in Hindi Matra (मात्रा).  It gets displaced for many words. See examples

सिलिएट_2
Label: सिलिएट

खरिदवाएँगीं_5
Label: खरिदवाएँगीं

See the change in what is there in the label as compared to in the image. I have tried different Devanagari fonts but the issue still persists.

**Comment by iknoorjobs** [comment]
Update: libraqm solves this issue.

**Pull request merged**
