### PR TITLE
Added character filtering functionality

### PR DESCRIPTION
**Pull request by YacobBY**
Exclusively allow or remove certain characters. 
Naming might have room for improvement but this is the clearest I could  think of.

### CODE REVIEW

**Comment by YacobBY** [comment]
Not sure why build crashes, it works fine for me

only

remove

**Comment by Belval** [comment]
According to the build logs, it fails because of invalid syntax. Is your code compatible with Python 3.5+

**Comment by YacobBY** [comment]
I'm running  python 3.7 myself, not sure if the re library changed between 3.5 and 3.7

**Comment by Belval** [comment]
run.py line 360

```
strings = [re.sub(f'[^{args.only}]', "", x) for x in strings]
```

**Comment by YacobBY** [comment]
I've seen where the error was in the builder, but that line runs perfectly fine for me. Could you try running it yourself?

**Comment by YacobBY** [comment]
Ok nevermind it works perfectly fine but because the default configuration didn't include any of the characters (A-H,Y) it empties the entire default string list and there's nothing left to generate. I'll put a return statement in if there's nothing left to generate.

**Pull request closed without merging**
